### ISSUE TITLE
Best way to reuse the same model for direct assessment and pairwise ranking

### ISSUE THREAD

**Issue by vionwinnie** [prometheus-eval/prometheus-eval#28]
Hello! Followed up on my previous issue, I am now able to load the model on A10G in `bfloat16` format. 

However, after I ran the judge snippet for direct assessment, I was not able to load another judge for pairwise because of OOM issues. 

Do you have suggestions on how to either
1) Clean up the memory/ garbage collection before importing for pairwise
2) Are there tricks to reuse the same model weights or the judge object in memory but for pairwise evaluation?

Thank you

**Comment by scottsuk0306** [comment]
Hi @vionwinnie ! Thanks for the good question! Actually you don't have to load a model again because our model is trained to do both task inherently. But to share some tricks to avoid CUDA OOM errors:

- Decrease `max_model_len`
- Decrease `gpu_memory_utilization`
- Use quantized version of Prometheus (Not supported in `prometheus-eval` library yet)

Because prometheus-eval library is built on top of `vllm`, I definitely recommend you to check the parameters of the [LLM class](https://docs.vllm.ai/en/latest/offline_inference/llm.html).
